### ISSUE TITLE
Uncaught ReferenceError: elemData is not defined

### ISSUE THREAD

**Issue by farrusete** [kartik-v/yii2-widget-select2#252]
Hi,

Seems that "Select all" option returns a console error since the last update:

```
Uncaught ReferenceError: elemData is not defined
    at HTMLLIElement.<anonymous> (select2-krajee.min.js:11)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at HTMLSpanElement.<anonymous> (select2-krajee.min.js:11)
    at HTMLSpanElement.dispatch (jquery.js:5206)
    at HTMLSpanElement.elemData.handle (jquery.js:5014)
```

This is how the dropdown looks in my code:

```
<?= $form->field($model, 'monthSearch')->widget(Select2::classname(), [
	'data' => 
		[
			1 => Yii::t('app', 'January'),
			2 => Yii::t('app', 'February'),
			3 => Yii::t('app', 'March'),
			4 => Yii::t('app', 'April'),
			5 => Yii::t('app', 'May'),
			6 => Yii::t('app', 'June'),
			7 => Yii::t('app', 'July'),
			8 => Yii::t('app', 'August'),
			9 => Yii::t('app', 'September'),
			10 => Yii::t('app', 'October'),
			11 => Yii::t('app', 'November'),
			12 => Yii::t('app', 'December'),
		],
	'showToggleAll' => true,
	'options' => [
		'multiple' => true,
		'class' => 'form-control',
		["typeSearch"=>['Selected'=>true]],
		'prompt' => Yii::t('app', 'Select Month')
	],
	'pluginOptions' => [
		'tags' => false,
		'allowClear' => true,
	],
])
->label(false); ?>
```
Thanks!

**Comment by kartik-v** [comment]
Fixed temporarily via #253... (related to #246 #247).... will need to study this.

**Comment by farrusete** [comment]
Thank you @kartik-v . It still returns the same error and Im not using template.

**Comment by pappfer** [comment]
Yeah, I have the same issue.
@kartik-v This problem still happens with the latest build. It is because the `select2-krajee.min.js` file is generated wrong. For some reasons the JS compressors make it wrong. It works fine when using the `select2-krajee.js` file instead of the minimized one.

**Comment by kartik-v** [comment]
Check if you have the same version as the  latest build in this repo... Cannot reproduce this... You can cross check on the demos page where it works fine with the minified js

**Comment by farrusete** [comment]
This has been fixed with the last update

Thank you @kartik-v
