### ISSUE TITLE
Bug on Select All Ajax

### ISSUE THREAD

**Issue by alexforte** [kartik-v/yii2-widget-select2#293]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-select2.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/select2).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (select2) issue. (Those should be directed to the [plugin issues repo](https://github.com/select2/select2/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Binding Select2 with Ajax call 
2. Open combo and Select All not show

## Expected behavior and actual behavior

When I open Select2 combo, I don't see Select All function

I was expecting to see it, also because is default value in documentation.
I just tried a lot of configuration parameters like (multiple = true, showToggleAll)
It's important to know that in previous version and with Array Data and not Ajax Call, the function is ok.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version:
- yii2-widget-select2 version: latest

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/select2)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
Seems to be some issue on your environment. Please check your code and whether you have the latest release of extension and the page is loading updated JS and CSS assets and not outdated  stale assets. This works fine as intended on the [demos page](https://demos.krajee.com/widget-details/select2#usage-sizes)... Please cross check.

**Comment by alexforte** [comment]
Hi Kartik, we done a good analysis and i want inform that problem It's not related to our environment.
Our last llibrary update (through composer) is **798dcea**, your latest commit. 
Please check code below to better understand problem.
This is control configuration:

`<?= $form->field($model, 'xyz')->widget(Select2::classname(), [
							'language' => 'it',
							'options' => ['placeholder' => Yii::t('app', 'Placeholder_Selezionare'),'multiple' => true],
							'pluginOptions' => [
								 'allowClear'=>true,'dropdownAutoWidth' => true,'minimumInputLength' => 5,
							    'ajax' => [
							        'url' => Url::to(['MyURL']),
							        'dataType' => 'json',
							        'data' => new JsExpression('function(params) { return {q:params.term}; }')
									],
							    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
							    'templateResult' => new JsExpression('function(data) { return data.text; }'),
							    'templateSelection' => new JsExpression('function (data) { return data.text; }'),
							],
])->label('MyLabel'); ?>`

There are no problems with data returned from Controller...

Now, as you can see from attacched images, no JS problem are raised from browser.
But the Select All function is not show.
This happens after last update.
![kartik1](https://user-images.githubusercontent.com/12466062/65032402-5f837e00-d943-11e9-982c-e59507bf17cc.jpg)
![kartik2](https://user-images.githubusercontent.com/12466062/65032403-5f837e00-d943-11e9-8f75-738b1e03a9a4.jpg)

**Comment by kartik-v** [comment]
Cross check if your browser is running old stale assets (clean your outdated web assets and clean browser cache and restart if needed)? The latest release is v2.1.4 (of the JS and CSS) where Select All functionality has been fixed to accomodate the select2 source plugin code changes. This works fine on the demos pages.

**Comment by alexforte** [comment]
We done all Cross check you required but problem still persist.
Problem is only present when source is AJAX.
In Demo Page is not present a Ajax example with multiple=true.
So i don't understand when u say "This works fine on the demos pages".
Can u give me link of this example where data source it's obtained from **AJAX** and property **multiple=true** ?
Thanks in advance for ur help.

**Comment by kartik-v** [comment]
Ok i see... Did not notice the ajax load part...It maybe due to new changes to the source plugin for ajax loaded content... Note that the latest version of the source select 2 plugin is now auto updated from. Packagisy...Reopening this issue for validating that
