### ISSUE TITLE
version 2.1.7 has not been released to packagist.org

### ISSUE THREAD

**Issue by lubobill1990** [kartik-v/yii2-widget-select2#308]
The bugfix in 2.1.7 is significant, so please release it to packagist.org.

**Comment by kambizzandi** [comment]
I agree, please release it to packagist.org

**Comment by kartik-v** [comment]
Done.

**Comment by lubobill1990** [comment]
https://packagist.org/packages/kartik-v/yii2-widget-select2 It seems it's still not updated.
